remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
# Customize the title, description, and other settings
title: Arjun Khatiwada
description: A Business Intelligence Analyst with Data Science skills.
# url: "https://yourdomain.com"  # Optional: Add your own domain or URL
# github_username: "aktrikx"   # Optional: Your GitHub username
